-- ============================================================
-- SGA LIN — Schema SQL Server (desarrollo local)
-- Ejecutar con: sqlcmd -S localhost -U sa -P SgaLocal2024! -i 01_schema.sql
-- ============================================================

USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'LIN')
    CREATE DATABASE LIN;
GO

USE LIN;
GO

-- ── ALMACENES ────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ALMACENES' AND type='U')
CREATE TABLE ALMACENES (
    ALMCOD  VARCHAR(10) NOT NULL PRIMARY KEY,
    ALMNOM  VARCHAR(60) NOT NULL
);
GO

-- ── EMPRESA ──────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='EMPRESA' AND type='U')
CREATE TABLE EMPRESA (
    EMPCOD     VARCHAR(10) NOT NULL PRIMARY KEY,
    EMPNOM     VARCHAR(80) NOT NULL,
    EMPALMCOD  VARCHAR(10) NOT NULL DEFAULT '',
    EMPTIPEMP  INT         NOT NULL DEFAULT 0,
    EMPCIF     VARCHAR(20) NULL,
    EMPDIR     VARCHAR(80) NULL,
    EMPPOB     VARCHAR(50) NULL,
    EMPTEL     VARCHAR(20) NULL,
    EMPEML     VARCHAR(80) NULL
);
GO
-- Columnas añadidas en v2 — seguras de ejecutar sobre tabla existente
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('EMPRESA') AND name='EMPCIF')
    ALTER TABLE EMPRESA ADD EMPCIF VARCHAR(20) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('EMPRESA') AND name='EMPDIR')
    ALTER TABLE EMPRESA ADD EMPDIR VARCHAR(80) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('EMPRESA') AND name='EMPPOB')
    ALTER TABLE EMPRESA ADD EMPPOB VARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('EMPRESA') AND name='EMPTEL')
    ALTER TABLE EMPRESA ADD EMPTEL VARCHAR(20) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('EMPRESA') AND name='EMPEML')
    ALTER TABLE EMPRESA ADD EMPEML VARCHAR(80) NULL;
GO

-- ── ARTICULO ─────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ARTICULO' AND type='U')
CREATE TABLE ARTICULO (
    ARTCOD      VARCHAR(30) NOT NULL PRIMARY KEY,
    ARTNOM      VARCHAR(80) NOT NULL,
    ARTCOD2     VARCHAR(30) NULL,
    ARTGRUCOD   VARCHAR(10) NULL,
    ARTSTOMIN   FLOAT       NOT NULL DEFAULT 0,
    ARTSTOMAX   FLOAT       NOT NULL DEFAULT 0,
    ARTMEDCOD   VARCHAR(10) NULL,
    ARTCOS      FLOAT       NOT NULL DEFAULT 0,
    ARTDES1     VARCHAR(80) NULL,
    ARTMAT      VARCHAR(30) NULL,
    ARTCOL      VARCHAR(20) NULL
);
GO

-- ── UBICACION ────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='UBICACION' AND type='U')
CREATE TABLE UBICACION (
    UBICODUBI    VARCHAR(20) NOT NULL PRIMARY KEY,
    UBIETI       VARCHAR(30) NULL,
    UBINOM       VARCHAR(60) NULL,
    UBIANC       FLOAT       NOT NULL DEFAULT 0,
    UBIALT       FLOAT       NOT NULL DEFAULT 0,
    UBINUMPAL    INT         NOT NULL DEFAULT 1,
    UBIMUL       BIT         NOT NULL DEFAULT 0,
    UBIALMCOD    VARCHAR(10) NOT NULL DEFAULT '',
    UBILIB       BIT         NOT NULL DEFAULT 0,
    UBINOROT     BIT         NOT NULL DEFAULT 0,
    UBINOAVIINV  BIT         NOT NULL DEFAULT 0,
    UBICON       VARCHAR(30) NULL
);
GO

-- ── STOCK ────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='STOCK' AND type='U')
CREATE TABLE STOCK (
    STOARTCOD  VARCHAR(30) NOT NULL,
    STOUBI     VARCHAR(20) NOT NULL,
    STOLOT     VARCHAR(30) NOT NULL DEFAULT '',
    STOCAN     FLOAT       NOT NULL DEFAULT 0,
    CONSTRAINT PK_STOCK PRIMARY KEY (STOARTCOD, STOUBI, STOLOT)
);
GO

-- ── STOCKLOTE ────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='STOCKLOTE' AND type='U')
CREATE TABLE STOCKLOTE (
    LOTARTCOD  VARCHAR(30) NOT NULL,
    LOTCOD     VARCHAR(30) NOT NULL,
    LOTFEC     DATE        NULL,
    LOTCAD     DATE        NULL,
    CONSTRAINT PK_STOCKLOTE PRIMARY KEY (LOTARTCOD, LOTCOD)
);
GO

-- ── ALBARANCS (movimientos) ───────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ALBARANCS' AND type='U')
CREATE TABLE ALBARANCS (
    ACSEMPCOD  VARCHAR(10)  NOT NULL DEFAULT '',
    ACSSER     VARCHAR(10)  NOT NULL,
    ACSNUM     INT          NOT NULL,
    ACSMOV     VARCHAR(4)   NOT NULL,
    ACSFEC     DATETIME     NOT NULL DEFAULT GETDATE(),
    ACSHOR     DATETIME     NULL,
    ACSARTCOD  VARCHAR(30)  NOT NULL,
    ACSUBI     VARCHAR(20)  NOT NULL DEFAULT '',
    ACSLOT     VARCHAR(30)  NULL,
    ACSCAN     FLOAT        NOT NULL DEFAULT 0,
    ACSCLICOD  VARCHAR(20)  NOT NULL DEFAULT '',
    ACSCLINOM  VARCHAR(80)  NULL,
    ACSNUMPIC  INT          NULL,
    ACSREPCOD  VARCHAR(20)  NULL,
    ACSNUMCAJ  INT          NULL,
    ACSNUMPAL  INT          NULL,
    ACSCENCOD  VARCHAR(10)  NULL
);
GO

CREATE INDEX IX_ALBARANCS_MOV  ON ALBARANCS (ACSMOV, ACSFEC);
CREATE INDEX IX_ALBARANCS_ART  ON ALBARANCS (ACSARTCOD, ACSFEC);
CREATE INDEX IX_ALBARANCS_NUM  ON ALBARANCS (ACSNUM, ACSSER);
GO

-- ── ARTICULOUBI (asignaciones artículo-ubicación) ─────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ARTICULOUBI' AND type='U')
CREATE TABLE ARTICULOUBI (
    ARTUBICODUBI   VARCHAR(20) NOT NULL,
    ARTUBIARTCOD   VARCHAR(30) NOT NULL,
    ARTUBIMIN      FLOAT       NOT NULL DEFAULT 0,
    ARTUBIMAX      FLOAT       NOT NULL DEFAULT 0,
    ARTUBIEXC      BIT         NOT NULL DEFAULT 0,
    ARTUBIALMCOD   VARCHAR(10) NOT NULL DEFAULT '',
    CONSTRAINT PK_ARTICULOUBI PRIMARY KEY (ARTUBICODUBI, ARTUBIARTCOD)
);
GO

-- ── ARTICULOSTOMIN (mínimos y máximos globales) ───────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ARTICULOSTOMIN' AND type='U')
CREATE TABLE ARTICULOSTOMIN (
    MINARTCOD  VARCHAR(30) NOT NULL PRIMARY KEY,
    MINSTOMIN  FLOAT       NOT NULL DEFAULT 0,
    MINSTOMAX  FLOAT       NOT NULL DEFAULT 0
);
GO

-- ── ARTICULOSINREP ────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ARTICULOSINREP' AND type='U')
CREATE TABLE ARTICULOSINREP (
    HISARTCOD  VARCHAR(30) NOT NULL PRIMARY KEY
);
GO

-- ── CLIENTE ───────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='CLIENTE' AND type='U')
CREATE TABLE CLIENTE (
    CLICOD  VARCHAR(20) NOT NULL PRIMARY KEY,
    CLINOM  VARCHAR(80) NOT NULL,
    CLIRAZ  VARCHAR(80) NULL
);
GO

-- ── PROVEEDOR ─────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='PROVEEDOR' AND type='U')
CREATE TABLE PROVEEDOR (
    PROVCOD  VARCHAR(20) NOT NULL PRIMARY KEY,
    PROVNOM  VARCHAR(80) NOT NULL,
    PROVRAZ  VARCHAR(80) NULL
);
GO

-- ── SUBFAMILIA ────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='SUBFAMILIA' AND type='U')
CREATE TABLE SUBFAMILIA (
    SFACOD   VARCHAR(10) NOT NULL PRIMARY KEY,
    SFANOM   VARCHAR(60) NOT NULL,
    SFANOLOT BIT         NOT NULL DEFAULT 0
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('SUBFAMILIA') AND name='SFANOLOT')
    ALTER TABLE SUBFAMILIA ADD SFANOLOT BIT NOT NULL DEFAULT 0;
GO

-- ── SGAUSUARIO ────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='SGAUSUARIO' AND type='U')
CREATE TABLE SGAUSUARIO (
    USUCOD  VARCHAR(20) NOT NULL PRIMARY KEY,
    USUNOM  VARCHAR(60) NOT NULL,
    USUTIP  VARCHAR(10) NULL,
    USUNIV  VARCHAR(10) NULL
);
GO

-- ── CONTADOR ──────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='CONTADOR' AND type='U')
CREATE TABLE CONTADOR (
    CONNUM  INT NOT NULL DEFAULT 1,
    REGMOD  INT NOT NULL DEFAULT 0
);
GO

-- ── LOG ───────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='LOG' AND type='U')
CREATE TABLE LOG (
    LOGID   INT IDENTITY(1,1) PRIMARY KEY,
    LOGFEC  DATETIME     NOT NULL DEFAULT GETDATE(),
    LOGMOV  VARCHAR(10)  NULL,
    LOGCOD  VARCHAR(30)  NULL,
    LOGDES  VARCHAR(200) NULL
);
GO

-- ── ARTICULOEXCLOTCLI ─────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ARTICULOEXCLOTCLI' AND type='U')
CREATE TABLE ARTICULOEXCLOTCLI (
    HISCON    INT IDENTITY(1,1) PRIMARY KEY,
    HISCLICOD VARCHAR(20) NOT NULL,
    HISARTCOD VARCHAR(30) NOT NULL,
    HISLOT    VARCHAR(30) NOT NULL DEFAULT ''
);
GO

-- ── ARTICULOLOTCLI ────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ARTICULOLOTCLI' AND type='U')
CREATE TABLE ARTICULOLOTCLI (
    HISCON    INT IDENTITY(1,1) PRIMARY KEY,
    HISCLICOD VARCHAR(20) NOT NULL,
    HISDIA    INT         NOT NULL DEFAULT 0
);
GO

-- ── ARTICULOLOTOBS ────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='ARTICULOLOTOBS' AND type='U')
CREATE TABLE ARTICULOLOTOBS (
    HISCON    INT IDENTITY(1,1) PRIMARY KEY,
    HISCLICOD VARCHAR(20) NOT NULL,
    HISARTCOD VARCHAR(30) NOT NULL,
    HISLOT    VARCHAR(30) NOT NULL DEFAULT '',
    HISOBS    VARCHAR(200) NULL
);
GO

-- ── SGA_PICKING_CONFIRMACION ──────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='SGA_PICKING_CONFIRMACION' AND type='U')
CREATE TABLE SGA_PICKING_CONFIRMACION (
    ID          INT IDENTITY(1,1) PRIMARY KEY,
    ALBARAN     INT         NOT NULL,
    SERIE       VARCHAR(10) NOT NULL,
    ARTICULO    VARCHAR(30) NOT NULL,
    UBICACION   VARCHAR(20) NOT NULL,
    LOTE        VARCHAR(30) NOT NULL DEFAULT '',
    OPERARIO    VARCHAR(50) NULL,
    FECHA_CONF  DATETIME    NOT NULL DEFAULT GETDATE()
);
GO

-- ── TERMINALPDA ───────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name='terminalpda' AND type='U')
CREATE TABLE terminalpda (
    repcod      VARCHAR(20) NOT NULL PRIMARY KEY,
    repnom      VARCHAR(60) NOT NULL,
    repser      VARCHAR(10) NULL,
    repdat      VARCHAR(10) NULL,
    reprutsin   VARCHAR(120) NULL,
    reprutwifi  VARCHAR(120) NULL
);
GO

PRINT 'Schema creado correctamente.';
GO
